export const BUILDINGS = [
  {
    id: "campfire",
    name: "Campfire",
    cost: { wood: 5 },
    unlockLevel: 1,
    score: 10,
    storageBonus: 5,
    warmthRadius: 3,
    effect: "Warm safe radius. Reduces night hunger drain nearby.",
    upgrade: {
      to: "bonfire",
      cost: { wood: 6, stone: 3 },
      effect: "Wider warmth radius. +5 more storage.",
    },
  },
  {
    id: "bonfire",
    name: "Bonfire",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 15,
    storageBonus: 10,
    warmthRadius: 5,
    effect: "Large warmth radius. Greatly reduces night hunger drain.",
  },
  {
    id: "shelter",
    name: "Shelter",
    cost: { wood: 10, stone: 5 },
    unlockLevel: 2,
    score: 22,
    storageBonus: 15,
    effect: "+15 storage capacity and slower hunger drain. Small stamina regen.",
    upgrade: {
      to: "cabin",
      cost: { wood: 8, stone: 4, planks: 3, coins: 2 },
      effect: "+10 more storage. Better hunger and stamina benefits.",
    },
  },
  {
    id: "cabin",
    name: "Cabin",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 35,
    storageBonus: 25,
    effect: "+25 storage total. Much slower hunger drain. Better stamina regen.",
  },
  {
    id: "farm",
    name: "Farm",
    cost: { wood: 8, water: 3 },
    unlockLevel: 3,
    score: 28,
    passive: { every: 30, gain: { food: 1 } },
    effect: "Grows food over time. Requires stored water to produce.",
    upgrade: {
      to: "irrigatedfarm",
      cost: { wood: 5, planks: 3, ingots: 1, coins: 2 },
      effect: "40% faster growth. No water consumption from inventory.",
    },
  },
  {
    id: "irrigatedfarm",
    name: "Irrigated Farm",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 40,
    passive: { every: 18, gain: { food: 1 } },
    effect: "Grows food quickly without consuming stored water.",
  },
  {
    id: "watchtower",
    name: "Watchtower",
    cost: { wood: 15, stone: 10 },
    unlockLevel: 4,
    score: 40,
    revealRadius: 5,
    effect: "Permanently reveals a wide watch radius.",
  },
  {
    id: "lumbercamp",
    name: "Lumber Camp",
    cost: { wood: 12, planks: 4 },
    unlockLevel: 4,
    score: 42,
    effect: "Automates +1 Wood every 18s. Consumes 1 Food per cycle.",
    upgrade: {
      to: "sawmill",
      cost: { wood: 6, planks: 4, ingots: 2, coins: 3 },
      effect: "Automates +2 Wood every 18s.",
    },
  },
  {
    id: "sawmill",
    name: "Sawmill",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 55,
    effect: "Automates +2 Wood every 18s. Consumes 1 Food per cycle.",
  },
  {
    id: "quarry",
    name: "Quarry",
    cost: { stone: 16, planks: 5 },
    unlockLevel: 4,
    score: 45,
    effect: "Automates +1 Stone every 22s. Consumes 1 Wood per cycle.",
    upgrade: {
      to: "deepquarry",
      cost: { stone: 10, planks: 4, ingots: 3, coins: 3 },
      effect: "Automates +2 Stone every 22s.",
    },
  },
  {
    id: "deepquarry",
    name: "Deep Quarry",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 60,
    effect: "Automates +2 Stone every 22s. Consumes 1 Wood per cycle.",
  },
  {
    id: "well",
    name: "Well",
    cost: { stone: 8, planks: 3 },
    unlockLevel: 3,
    score: 30,
    effect: "Automates +1 Water every 16s. Free to operate.",
    upgrade: {
      to: "deepwell",
      cost: { stone: 8, planks: 4, ingots: 2, coins: 2 },
      effect: "Automates +2 Water every 16s.",
    },
  },
  {
    id: "deepwell",
    name: "Deep Well",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 42,
    effect: "Automates +2 Water every 16s. Free to operate.",
  },
  {
    id: "forge",
    name: "Forge",
    cost: { stone: 20, wood: 10 },
    unlockLevel: 5,
    score: 55,
    unlocksUpgrade: true,
    effect: "Unlocks iron tool upgrades with faster gathering and bonus yield.",
    upgrade: {
      to: "blastfurnace",
      cost: { stone: 12, ingots: 5, planks: 4, coins: 5 },
      effect: "Smelt ingots 30% cheaper. Unlocks Tier III tool upgrades.",
    },
  },
  {
    id: "blastfurnace",
    name: "Blast Furnace",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 75,
    unlocksUpgrade: true,
    effect: "Cheaper ingot smelting. Unlocks Tier III tool upgrades.",
  },
  {
    id: "workshop",
    name: "Workshop",
    cost: { wood: 12, stone: 8, planks: 4 },
    unlockLevel: 5,
    score: 58,
    effect: "Automates plank crafting from Wood.",
    upgrade: {
      to: "factory",
      cost: { wood: 8, planks: 6, ingots: 3, coins: 4 },
      effect: "More efficient plank crafting.",
    },
  },
  {
    id: "factory",
    name: "Factory",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 72,
    effect: "Automates plank crafting efficiently.",
  },
  {
    id: "market",
    name: "Market",
    cost: { wood: 20, stone: 20, planks: 8, ingots: 4 },
    unlockLevel: 6,
    score: 100,
    winCondition: true,
    trade: true,
    effect: "Opens trade and completes the empire victory.",
    upgrade: {
      to: "tradehub",
      cost: { wood: 15, planks: 10, ingots: 6, coins: 15 },
      effect: "Better trade rates and coin production.",
    },
  },
  {
    id: "tradehub",
    name: "Trade Hub",
    cost: null,
    unlockLevel: 99,
    hidden: true,
    score: 140,
    trade: true,
    effect: "Better trade rates. Coins craft +1 extra.",
  },
];

export function getBuildingById(id) {
  return BUILDINGS.find((building) => building.id === id) || null;
}

export function getVisibleBuildings() {
  return BUILDINGS.filter((b) => !b.hidden);
}
